# SAMPLING_RATE = 128  # In hertz
SAMPLING_RATE = 8  # In hertz
NUMBER_OF_CHANNEL = 14
EEG_IN_SECONDS = 1  # time image
SIZE_RAW_DATA = SAMPLING_RATE * EEG_IN_SECONDS
SECONDS_RECORD = 5
WINDOW_SIZE = 1
VERSION = "V13"
